Agendamento/Controllers/TipoExameController.cs
using Application.InputModel;
using Application.ViewModel;
using Core.Entity;
using Core.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Agendamento.Controllers
{
    public class TipoExameController : Controller
    {

        private readonly IGenericoRepository<TipoDeExame> _genericoRepository;

        public TipoExameController(IGenericoRepository<TipoDeExame> genericoRepository)
        {
            _genericoRepository = genericoRepository;
        }

        // GET: TipoDeExameController
        public ActionResult Index()
        {
            var tipoDeExameViewModel = new List<TipoDeExameViewModel>();

            var tiposDeExame = _genericoRepository.ObterTodos();

            foreach (var item in tiposDeExame)
            {
                tipoDeExameViewModel.Add(new TipoDeExameViewModel(item.Id, item.NomeDoTipo, item.Descricao, item.Exames));
            }

            return View(tipoDeExameViewModel);
        }

        // GET: TipoDeExameController/Details/5
        public ActionResult Details(int id)
        {
            var tipoDeExame = _genericoRepository.ObterUm(id);

            var tipoDeExameinputModel = new TipoDeExameInputModel
            {
                NomeDoTipo = tipoDeExame.NomeDoTipo,
                Descricao = tipoDeExame.Descricao,


            };

            return View(tipoDeExameinputModel);
        }

        // GET: TipoDeExameController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoDeExameController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoDeExameInputModel model)
        {
            try
            {
                var tiposDeExame = new TipoDeExame(model.Id, model.NomeDoTipo, model.Descricao);
                _genericoRepository.Cadastro(tiposDeExame);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoDeExameController/Edit/5
        public ActionResult Edit(int id)
        {
            var tipoDeExame = _genericoRepository.ObterUm(id);

            var tipodeExameInputModel = new TipoDeExameInputModel
            {
                NomeDoTipo = tipoDeExame.NomeDoTipo,
                Descricao = tipoDeExame.Descricao,

            };
            return View(tipodeExameInputModel);
        }

        // POST: TipoDeExameController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TipoDeExameInputModel tipoDeExameInput)
        {
            try
            {
                var tipoDexame = new TipoDeExame(tipoDeExameInput.Id, tipoDeExameInput.NomeDoTipo, tipoDeExameInput.Descricao);

                _genericoRepository.Atualizar(id, tipoDexame);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoDeExameController/Delete/5
        public ActionResult Delete(int id)
        {
            var tipoDeExame = _genericoRepository.ObterUm(id);

            var tipoDeExameinputModel = new TipoDeExameInputModel
            {
                NomeDoTipo = tipoDeExame.NomeDoTipo,
                Descricao = tipoDeExame.Descricao,


            };

            return View(tipoDeExameinputModel);
        }

        // POST: TipoDeExameController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _genericoRepository.Deletar(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Agendamento/Views/TipoExame/Create.cshtml
@model Application.InputModel.TipoDeExameInputModel
@{
}
<div class="row">
    <div class="col-md-6 d-none d-md-block" style="height: 450px;">
        <div class="text-center col-md-12 my-auto side-heder">
            <h1>Tipos de exames</h1>
            <img src="~/TipoExame.png" width="540" height="350" />
        </div>
    </div>
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">Nome</label>
                <input asp-for="NomeDoTipo" class="form-control"/>
                <span asp-validation-for="NomeDoTipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control"  />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                
            </div>
            <div class="form-group">
                <a class="btn btn-outline-secondary" asp-controller="TipoExame" asp-action="Index">Voltar</a>

                <input type="submit" value="Salvar" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

Agendamento/Views/TipoExame/Delete.cshtml
@model Application.InputModel.TipoDeExameInputModel

@{ ViewData["Title"] = "Delete"; }

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeDoTipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeDoTipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
       

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
    </form>
</div>

Agendamento/Views/TipoExame/Details.cshtml
@model Application.InputModel.TipoDeExameInputModel

@{ ViewData["Title"] = "Details"; }

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeDoTipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeDoTipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        
    </dl>
</div>
<div>
    |
    <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
</div>

Agendamento/Views/TipoExame/Edit.cshtml
@model Application.InputModel.TipoDeExameInputModel

@{ ViewData["Title"] = "Edit"; }

<h1>Editar tipo de exame</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="NomeDoTipo" class="form-control" maxlength="100" />
                <span asp-validation-for="NomeDoTipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control" maxlength="256" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index" asp-controller="TipoExame" class="btn btn-outline-secondary">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agendamento/Views/TipoExame/Index.cshtml
@model IEnumerable<Application.ViewModel.TipoDeExameViewModel>

@{ ViewData["Title"] = "Index"; }


<p>
    <a  class="btn " style="background-color: #ffce64;" asp-action="Create">Novo tipo de exame</a>
</p>

<table class="table table-striped table-hover">
    <thead class="thead-light">
        <tr>
            <th>
                Nome
            </th>
            <th>
                Descrição
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeDoTipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>

                <td>
                    <a asp-action="Edit" style="width:30px" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" style="width:30px" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" style="width:30px" asp-route-id="@item.Id">delete</a>
                </td>
            </tr>

        }
    </tbody>