Agendamento/Controllers/ExameController.cs
using Application.InputModel;
using Application.Serviços.Interface;
using Application.ViewModel;
using Core.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Agendamento.Controllers
{
    public class ExameController : Controller
    {
        private readonly IGenericoServico<Exame> _genericoServicoExame;
        private readonly IGenericoServico<TipoDeExame> _genericoServicoTipoExame;

        public ExameController(IGenericoServico<Exame> genericoServicoExame, IGenericoServico<TipoDeExame> genericoServicoTipoExame)
        {
            _genericoServicoExame = genericoServicoExame;
            _genericoServicoTipoExame = genericoServicoTipoExame;
        }
        // GET: ExameController
        public ActionResult Index()
        {
            var exames = _genericoServicoExame.ObterTodos();
            var examesViewModel = new List<ExameViewModel>();
            foreach (var item in exames)
            {
                examesViewModel.Add(new ExameViewModel(item.Id, item.NomeDoExame, item.Observacao, item.IdTipoExame, _genericoServicoTipoExame.ObterUm(item.IdTipoExame)));
            }
            return View(examesViewModel);
        }

        // GET: ExameController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        private void PopularTipoExames()
        {
            var tiposExames = _genericoServicoTipoExame.ObterTodos().Select(te => new SelectListItem
            {
                Value = te.Id.ToString(),
                Text = te.NomeDoTipo
            }).ToList();
            ViewBag.TiposExame = tiposExames;
        }

        // GET: ExameController/Create
        public ActionResult Create()
        {
            PopularTipoExames();
            return View();
        }

        // POST: ExameController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] ExameInputModel exameInputModel)
        {

            if (ModelState.IsValid)
            {
                var exame = new Exame(exameInputModel.Id, exameInputModel.NomeDoExame, exameInputModel.Observacao, exameInputModel.IdTipoExame);
                _genericoServicoExame.Cadastro(exame);

                return RedirectToAction(nameof(Index));
            }
            PopularTipoExames();

            return View("Create");

        }

        // GET: ExameController/Edit/5
        public ActionResult Edit(int id)
        {
            PopularTipoExames();
            var exame = _genericoServicoExame.ObterUm(id);

            var exameInputModel = new ExameInputModel {
                Id= exame.Id,
                NomeDoExame= exame.NomeDoExame,
                Observacao = exame.Observacao,
                IdTipoExame = exame.IdTipoExame 
            };
            
            return View(exameInputModel);
        }

        // POST: ExameController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ExameInputModel  inputModel)
        {
            PopularTipoExames();
            try
            {
                if (ModelState.IsValid)
                {
                    var exame = new Exame(inputModel.Id, inputModel.NomeDoExame, inputModel.Observacao, inputModel.IdTipoExame);
                    _genericoServicoExame.Atualizar(id, exame);
                    return RedirectToAction(nameof(Index)); 
                }
                else
                {
                    return View("Edit");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: ExameController/Delete/5
        public ActionResult Delete(int id)
        {
            var exame = _genericoServicoExame.ObterUm(id);
            var exameViewModel = new ExameViewModel(exame.Id, exame.NomeDoExame, exame.Observacao, exame.IdTipoExame, exame.TipoDeExame);
            return View(exameViewModel);
        }

        // POST: ExameController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _genericoServicoExame.Deletar(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Agendamento/Controllers/PacienteController.cs
using Agendamento.Models;
using Application.InputModel;
using Application.Serviços.Interface;
using Application.ViewModel;
using Core.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Agendamento.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IPacienteServico _pacienteServico;

        public PacienteController(IPacienteServico pacienteServico)
        {
            _pacienteServico = pacienteServico;
        }
        // GET: PacienteController
        public ActionResult Index()
        {
            var pacienteViewModels = new List<PacienteViewModel>();

            var pacientes = _pacienteServico.ObterTodos();

            foreach (var item in pacientes)
            {
                pacienteViewModels.Add(new PacienteViewModel(item.Id, item.Nome, item.CPF, item.DataNascimento, item.Telefone, item.Email, item.Sexo));
            }

            return View(pacienteViewModels);
        }

        // GET: PacienteController/Details/5
        public ActionResult Details(int id)
        {

            var paciente = _pacienteServico.ObterUm(id);

            var pacienteInputModel = new PacienteInputModel
            {
                Nome = paciente.Nome,
                CPF = paciente.CPF,
                DataNscimento = paciente.DataNascimento,
                Telefone = paciente.Telefone,
                Email = paciente.Email,


            };

            return View(pacienteInputModel);
        }

        // GET: PacienteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PacienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PacienteInputModel model)
        {
            if (ModelState.IsValid)
            {
                var paciente = new Paciente(model.Id, model.Nome, model.CPF, model.DataNscimento, model.Telefone, model.Email, model.Sexo);
                _pacienteServico.Cadastro(paciente); 
                return RedirectToAction(nameof(Index));
            }


            return View();
        }

        // GET: PacienteController/Edit/5
        public ActionResult Edit(int id)
        {


            var paciente = _pacienteServico.ObterUm(id);

            var pacienteInputModel = new PacienteInputModel
            {
                Nome = paciente.Nome,
                CPF = paciente.CPF,
                DataNscimento = paciente.DataNascimento,
                Telefone = paciente.Telefone,
                Email = paciente.Email,

            };
           
            return View(pacienteInputModel);
        }

        // POST: PacienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PacienteInputModel pacienteimput)
        {
            try
            {
                var paciente = new Paciente(pacienteimput.Id, pacienteimput.Nome, pacienteimput.CPF, pacienteimput.DataNscimento, pacienteimput.Telefone, pacienteimput.Email, pacienteimput.Sexo); 

                _pacienteServico.Atualizar(id, paciente);
                
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PacienteController/Delete/5
        public ActionResult Delete(int id)
        {
            var paciente = _pacienteServico.ObterUm(id);

            var pacienteInputModel = new PacienteInputModel
            {
                Nome = paciente.Nome,
                CPF = paciente.CPF,
                DataNscimento = paciente.DataNascimento,
                Telefone = paciente.Telefone,
                Email = paciente.Email,

            };

            return View(pacienteInputModel);
        }

        // POST: PacienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

                _pacienteServico.Deletar(id);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Agendamento/Views/Exame/Create.cshtml
@model Application.InputModel.ExameInputModel
@{
}

<div class="row">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="control-label">Nome do exame</label>
            <input asp-for="NomeDoExame" class="form-control" maxlength="100" />
            <span asp-validation-for="NomeDoExame" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="control-label">Observação</label>
            <textarea asp-for="Observacao" maxlength="1000" class="form-control"></textarea>
            <span asp-validation-for="Observacao" class="text-danger"></span>
        </div>
      
        <div class="form-group">
            <label class="control-label">Tipos de exames</label>
            @Html.DropDownListFor(m => m.IdTipoExame, (IEnumerable<SelectListItem>)ViewBag.TiposExame, "Selecione", new { @id = "comboTipoExame", @class = "form-control" })
            <span asp-validation-for="IdTipoExame" class="text-danger"></span>
        </div>
        <div class="form-group">
            <a class="btn btn-outline-secondary" asp-controller="Paciente" asp-action="Index">Voltar</a>
            <input type="submit" value="Salvar" class="btn btn-outline-primary" />
        </div>
    </form>

    <!-- <section class="col col-3">
        <div class="required">
            <label for="comboTorre" class="control-label">Tipos de exames</label>
        </div>
    </section>
        -->


</div>

Agendamento/Views/Exame/Delete.cshtml
@model Application.ViewModel.ExameViewModel

@{ ViewData["Title"] = "Delete"; }

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeDoExame)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDeExame.NomeDoTipo)
        </dt>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
    </form>
</div>

Agendamento/Views/Exame/Details.cshtml
@model Application.ViewModel.ExameViewModel

@{ ViewData["Title"] = "Details"; }

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeDoExame)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Observacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDeExame.NomeDoTipo)
        </dt>
    </dl>
</div>
<div>
    |
    <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
</div>

Agendamento/Views/Exame/Edit.cshtml
@model Application.InputModel.ExameInputModel

@{ ViewData["Title"] = "Edit"; }

<h1>Editar Paciente</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Nome do exame</label>
                <input asp-for="NomeDoExame" class="form-control" maxlength="100" />
                <span asp-validation-for="NomeDoExame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Observação</label>
                <textarea asp-for="Observacao" maxlength="1000" class="form-control"></textarea>
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Tipos de exames</label>
                @Html.DropDownListFor(m => m.IdTipoExame, (IEnumerable<SelectListItem>)ViewBag.TiposExame, "Selecione", new { @id = "comboTipoExame", @class = "form-control" })
                <span asp-validation-for="IdTipoExame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a class="btn btn-outline-secondary" asp-controller="Exame" asp-action="Index">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agendamento/Views/Exame/Index.cshtml
@model IEnumerable<Application.ViewModel.ExameViewModel>

@{ ViewData["Title"] = "Index"; }


<p>
    <a class="btn" style="background-color: #ffce64;" asp-action="Create">Novo Exame</a>
</p>
<table class="table table-striped table-hover">
    <thead class="thead-light">
        <tr>
            <th>
               Nome do exame
            </th>
            <th>
                Observação
            </th>
            <th>
                Tipo do exame
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeDoExame)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Observacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDeExame.NomeDoTipo)
                </td>
                <td>
                    <a asp-action="Edit" style="width:30px" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Delete" style="width:30px" asp-route-id="@item.Id">delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>